#!/usr/bin/env python3
"""Generate PDG's standard dimension enum/table from upstream PDAL JSON."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


TYPE_MAP = {
    "double": "Double",
    "float": "Float",
    "int32": "Signed32",
    "int64_t": "Signed64",
    "uint8": "Unsigned8",
    "uint8_t": "Unsigned8",
    "uint16": "Unsigned16",
    "uint32": "Unsigned32",
    "uint64": "Unsigned64",
}


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input", type=Path, default=root / "pdal" / "Dimension.json"
    )
    parser.add_argument(
        "--header",
        type=Path,
        default=root / "include" / "pdg" / "generated" / "Dimensions.hpp",
    )
    parser.add_argument(
        "--table",
        type=Path,
        default=root / "src" / "core" / "generated" / "Dimensions.inc",
    )
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def load_dimensions(path: Path) -> tuple[list[dict[str, object]], str]:
    raw = path.read_bytes()
    document = json.loads(raw)
    dimensions = document.get("dimensions")
    if not isinstance(dimensions, list) or not dimensions:
        raise ValueError(f"{path}: expected a non-empty dimensions array")

    seen_names: set[str] = set()
    seen_lookup: dict[str, str] = {}
    for dimension in dimensions:
        if not isinstance(dimension, dict):
            raise ValueError(f"{path}: dimension entries must be objects")
        name = dimension.get("name")
        type_name = dimension.get("type")
        if not isinstance(name, str) or not re.fullmatch(
            r"[A-Za-z_][A-Za-z0-9_]*", name
        ):
            raise ValueError(f"{path}: invalid dimension name {name!r}")
        if name in seen_names:
            raise ValueError(f"{path}: duplicate dimension name {name}")
        if type_name not in TYPE_MAP:
            raise ValueError(f"{path}: unsupported type {type_name!r} for {name}")
        seen_names.add(name)

        lookup_names = [name, *aliases(dimension)]
        for lookup_name in lookup_names:
            folded = lookup_name.upper()
            previous = seen_lookup.get(folded)
            if previous is not None and previous != name:
                raise ValueError(
                    f"{path}: lookup name {lookup_name!r} maps to both "
                    f"{previous} and {name}"
                )
            seen_lookup[folded] = name

    return dimensions, hashlib.sha256(raw).hexdigest()


def aliases(dimension: dict[str, object]) -> list[str]:
    value = dimension.get("alt_names")
    if value is None:
        return []
    if isinstance(value, str):
        result = [item.strip() for item in value.split(",") if item.strip()]
    elif isinstance(value, list) and all(isinstance(item, str) for item in value):
        result = [item.strip() for item in value if item.strip()]
    else:
        raise ValueError(f"invalid alt_names for {dimension.get('name')}")
    for name in result:
        if not name or "\x00" in name:
            raise ValueError(f"invalid alternate dimension name {name!r}")
    return result


def render_header(dimensions: list[dict[str, object]], digest: str) -> str:
    entries = ["    Unknown = 0,"]
    for index, dimension in enumerate(dimensions, start=1):
        entries.append(f"    {dimension['name']} = {index},")
    entries.append(f"    Count = {len(dimensions) + 1}")
    return "\n".join(
        [
            "// Generated by scripts/pdg/generate_dimensions.py; do not edit.",
            f"// Source pdal/Dimension.json SHA-256: {digest}",
            "#pragma once",
            "",
            "#include <cstdint>",
            "",
            "namespace pdg",
            "{",
            "enum class StandardDimension : std::uint16_t",
            "{",
            *entries,
            "};",
            "} // namespace pdg",
            "",
        ]
    )


def render_table(dimensions: list[dict[str, object]], digest: str) -> str:
    lines = [
        "// Generated by scripts/pdg/generate_dimensions.py; do not edit.",
        f"// Source pdal/Dimension.json SHA-256: {digest}",
    ]
    for index, dimension in enumerate(dimensions, start=1):
        lines.append(
            f"PDG_DIMENSION({dimension['name']}, {index}U, "
            f'"{dimension["name"]}", {TYPE_MAP[str(dimension["type"])]})'
        )
    for dimension in dimensions:
        for alias in aliases(dimension):
            lines.append(
                f"PDG_ALIAS({json.dumps(alias)}, {dimension['name']})"
            )
    lines.append("")
    return "\n".join(lines)


def update(path: Path, content: str, check: bool) -> bool:
    existing = path.read_text() if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"generated file is stale: {path}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"updated {path}")
    return True


def main() -> int:
    args = parse_args()
    try:
        dimensions, digest = load_dimensions(args.input)
        header = render_header(dimensions, digest)
        table = render_table(dimensions, digest)
        valid = update(args.header, header, args.check)
        valid = update(args.table, table, args.check) and valid
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(error, file=sys.stderr)
        return 2
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
